/**
 * Bundle workers/edge-router-worker.js (+ workers/lib/) into the single
 * deployable file at src/edge-router-worker.js.
 *
 * Usage: npm run build   (or: node build.mjs)
 *
 * This repo is the source of truth for the customer-zone edge-router worker.
 * `src/edge-router-worker.js` is a COMMITTED build artifact: it is what the
 * Deploy-to-Cloudflare button deploys (wrangler.jsonc `main`), and what NORG's
 * backend pins by commit SHA + SHA-256 and materialises for API-token installs
 * (content-craft `edge_worker_pin.py` / `sync-edge-router.mjs`). CI rebuilds
 * it and fails on any diff, so a source edit can never ship without its bundle.
 *
 * Deployment surfaces need ONE self-contained file, so the lib modules are
 * inlined. Two guards run on the result before it is written: no NORG-internal
 * secret name may appear (this file ships into third-party accounts), and the
 * bundle must be import-free (`export default { fetch, scheduled }` is how a
 * Workers module registers handlers and must stay).
 *
 * esbuild is invoked through npx with a PINNED version rather than as a
 * package.json dependency, so the build is zero-install and deterministic.
 */

import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ESBUILD_VERSION = "0.25.5";

const here = dirname(fileURLToPath(import.meta.url));
const entry = join(here, "workers", "edge-router-worker.js");
const outfile = join(here, "src", "edge-router-worker.js");

// Names that must NEVER appear in a bundle that ships into a customer's
// Cloudflare account. Mirrors the deploy-time guard in content-craft's
// worker_source.py, which refuses to upload a leaking artifact.
const FORBIDDEN_NAMES = [
  "CRAWLER_EVENT_SECRET",
  "WORKER_AUTH_SECRET",
  "R2_ACCESS_KEY_ID",
  "R2_SECRET_ACCESS_KEY",
  "INTERNAL_API_KEY",
  "EDGE_BUCKET",
];

mkdirSync(dirname(outfile), { recursive: true });
execFileSync(
  "npx",
  [
    "--yes",
    `esbuild@${ESBUILD_VERSION}`,
    entry,
    "--bundle",
    "--format=esm",
    "--platform=neutral",
    "--legal-comments=inline",
    `--outfile=${outfile}`,
    "--banner:js=// GENERATED by build.mjs — do not edit.\n// Source: workers/edge-router-worker.js (+ workers/lib/).",
  ],
  { stdio: "inherit" },
);
// A bundle that fails to parse must fail the build, not the deploy.
execFileSync("node", ["--check", outfile], { stdio: "inherit" });

const bundle = readFileSync(outfile, "utf8");
for (const name of FORBIDDEN_NAMES) {
  if (bundle.includes(name)) {
    throw new Error(
      `refusing to publish: bundle contains forbidden name "${name}" — this must never reach a customer account`,
    );
  }
}
// Only a real ES module import statement is forbidden; the export default
// that registers the Workers handlers must stay.
if (/^\s*import\s+.*\sfrom\s+['"]/m.test(bundle)) {
  throw new Error("refusing to publish: bundle is not import-free");
}

const version = /EDGE_SCRIPT_VERSION\s*=\s*"([^"]+)"/.exec(bundle)?.[1];
console.log(`built src/edge-router-worker.js (EDGE_SCRIPT_VERSION ${version})`);
