/**
 * Bundle bunny/src/ into the single deployable file at
 * bunny/dist/edge-router-bunny.js.
 *
 * Usage: node bunny/build.mjs   (or: npm run build:bunny)
 *
 * Bunny's API takes the script as ONE string — `POST /compute/script/{id}/code`
 * has a single `Code` field — so the adapters and everything they import from
 * core/ must be inlined. dist/edge-router-bunny.js is therefore a COMMITTED
 * build artifact, the same arrangement as src/edge-router-worker.js for
 * Cloudflare and aws/src/ for Lambda@Edge: install.mjs uploads exactly this
 * file, and CI rebuilds it and fails on any diff, so a source edit can never
 * ship without its bundle.
 *
 * The Bunny SDK import is marked EXTERNAL and survives into the bundle: it is
 * a bare specifier that only Bunny's Deno runtime can resolve, and it must be
 * pinned so a deploy is reproducible. Everything else must be inlined, which
 * the guards below assert.
 *
 * esbuild is invoked through npx with a PINNED version rather than as a
 * package.json dependency, so the build is zero-install and deterministic.
 */

import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ESBUILD_VERSION = "0.25.5";

const here = dirname(fileURLToPath(import.meta.url));
const entry = join(here, "src", "index.js");
const outfile = join(here, "dist", "edge-router-bunny.js");

// The only import allowed to survive bundling. Anything else means a module
// failed to inline and the upload would fail to start at the edge.
const ALLOWED_IMPORT = "@bunny.net/edgescript-sdk@";

// Names that must NEVER appear in a bundle that ships into a customer's Bunny
// account. Mirrors the deploy-time guard in content-craft's worker_source.py.
const FORBIDDEN_NAMES = [
  "CRAWLER_EVENT_SECRET",
  "WORKER_AUTH_SECRET",
  "R2_ACCESS_KEY_ID",
  "R2_SECRET_ACCESS_KEY",
  "INTERNAL_API_KEY",
  "EDGE_BUCKET",
];

mkdirSync(dirname(outfile), { recursive: true });
execFileSync(
  "npx",
  [
    "--yes",
    `esbuild@${ESBUILD_VERSION}`,
    entry,
    "--bundle",
    "--format=esm",
    "--platform=neutral",
    "--external:@bunny.net/*",
    "--external:node:*",
    "--legal-comments=inline",
    `--outfile=${outfile}`,
    "--banner:js=// GENERATED by bunny/build.mjs — do not edit.\n// Source: bunny/src/ (+ core/, workers/lib/).",
  ],
  { stdio: "inherit" },
);
// A bundle that fails to parse must fail the build, not the deploy.
execFileSync("node", ["--check", outfile], { stdio: "inherit" });

const bundle = readFileSync(outfile, "utf8");
for (const name of FORBIDDEN_NAMES) {
  if (bundle.includes(name)) {
    throw new Error(
      `refusing to publish: bundle contains forbidden name "${name}" — this must never reach a customer account`,
    );
  }
}

const imports = [...bundle.matchAll(/^\s*import\s+[^\n]*?from\s+["']([^"']+)["']/gm)].map(
  (m) => m[1],
);
const stray = imports.filter(
  (spec) => !spec.startsWith(ALLOWED_IMPORT) && !spec.startsWith("node:"),
);
if (stray.length) {
  throw new Error(`refusing to publish: bundle has unresolved imports ${stray.join(", ")}`);
}
if (!imports.some((spec) => spec.startsWith(ALLOWED_IMPORT))) {
  throw new Error(
    "refusing to publish: the Bunny SDK import is missing or unpinned — it must read " +
      `"${ALLOWED_IMPORT}<version>"`,
  );
}

const version = /EDGE_SCRIPT_VERSION\s*=\s*"([^"]+)"/.exec(bundle)?.[1];
console.log(`built bunny/dist/edge-router-bunny.js (EDGE_SCRIPT_VERSION ${version})`);
