/**
 * Talking to the customer's origin, and handing control back to Fastly.
 *
 * @description Fastly adapter for origin fetches and passthrough.
 *
 * This is where Fastly is markedly simpler than CloudFront, and the difference
 * is worth stating because it removes two whole classes of bug we hit there:
 *
 *  - **Passthrough is a real fetch, not a sentinel.** On Lambda@Edge "serve the
 *    origin" means returning a mutated request object and letting CloudFront go
 *    fetch it, which is why the Host header had to be rewritten and why an
 *    unhandled throw became a 502. Here `fetch(request, { backend })` returns a
 *    Response like any other, so the top-level catch can simply return the
 *    origin — the same shape as the Cloudflare worker.
 *  - **No generated-response size cap.** CloudFront refuses a generated
 *    origin-request response over 1 MB. Fastly has a 128 MB heap and streams,
 *    so a mirror of any realistic size is returned inline and always carries
 *    its X-Norg-Edge headers. The whole origin-switch fallback that CloudFront
 *    needed does not exist here.
 *
 * THE PAGE IS NEVER CACHED AT THE EDGE. A Compute `fetch` to a backend goes
 * through Fastly's cache by default, so a cacheable origin page would be
 * stored and replayed — and every replay is a request this code never saw. The
 * adapter therefore fetches every page with a pass override (a `CacheOverride`
 * the entry point builds, because the `fastly:` modules cannot be imported
 * under Node), so the origin answers every page request exactly as it would
 * without a CDN. Static assets are the one exception and keep Fastly's normal
 * caching: they are never a mirrorable document, and un-caching them would
 * cost the customer for nothing.
 */

import { LOOP_GUARD_HEADER } from "../../../core/constants.mjs";
import { isStaticAssetPath } from "../../../core/paths.js";

/** Backend name for the customer's own origin, defined in fastly.toml. */
export const ORIGIN_BACKEND = "customer_origin";

/**
 * Fetch options for a request to the origin: the backend, and no cache for a
 * page.
 *
 * @param {Request} request The request being sent.
 * @param {Object} env Install config, which may carry EDGE_PASS_CACHE.
 * @returns {Object} RequestInit for fetch.
 */
export function originFetchInit(request, env) {
  const init = { backend: ORIGIN_BACKEND };
  const pass = env && env.EDGE_PASS_CACHE;
  if (pass && !isStaticAssetPath(new URL(request.url).pathname)) init.cacheOverride = pass;
  return init;
}

/**
 * Fetch the customer's origin, for a branch that must read the body.
 *
 * Carries the viewer's headers so the origin sees the request it would have
 * seen anyway, plus the loop guard so a misconfigured service cannot recurse
 * into this code. Never cached: the bytes are measured and re-served here.
 *
 * Deliberately does NOT rewrite the Host header. Fastly sends the request's own
 * Host to the backend, which is what a host-aware origin needs — absolute URLs,
 * canonical tags, cookie domains and auth middleware all key off it. (On
 * CloudFront the platform forces the opposite, and it bounced every visitor off
 * the CDN domain until we understood why.)
 *
 * @param {Request} request Incoming request.
 * @param {Object} env Install config.
 * @returns {Promise<Response>} Origin response.
 */
export function fetchOrigin(request, env) {
  const headers = new Headers(request.headers);
  headers.set(LOOP_GUARD_HEADER, "1");
  return fetch(new Request(request, { headers }), originFetchInit(request, env));
}

/**
 * Pass the request to the origin untouched.
 *
 * The terminal state of every failure path. Unlike CloudFront this is an
 * ordinary Response rather than a sentinel — but see safePassthrough below
 * before treating it as infallible.
 *
 * @param {Request} request Incoming request.
 * @param {Object} env Install config.
 * @returns {Promise<Response>} Origin response.
 */
export function passthrough(request, env) {
  return fetch(request, originFetchInit(request, env));
}

/**
 * Passthrough that cannot itself throw.
 *
 * WHY THIS EXISTS, AND DO NOT COLLAPSE IT BACK INTO passthrough(). On
 * Cloudflare a fetch to an unreachable origin RESOLVES with a platform error
 * response (522/525), so `return fetch(request)` in a catch block is genuinely
 * the end of the line. On Fastly a backend connection error — origin down, DNS
 * failure, TLS failure, timeout — REJECTS. That means the obvious
 * `catch { return passthrough(request) }` is not a safety net at all: the
 * rejection escapes respondWith and the visitor gets a 500 generated by us, on
 * a request we were only ever meant to hand back untouched. Verified against
 * the real Wasm under Viceroy, where every request 500ed with the origin down.
 *
 * A service with no Compute code at all answers an unreachable backend with
 * Fastly's own 503, so that is the honest parity: we return the error the
 * platform would have returned anyway, never one we invented.
 *
 * @param {Request} request Incoming request.
 * @param {Object} env Install config.
 * @returns {Promise<Response>} Origin response, or a 503 matching the
 *   platform's own behaviour when the origin cannot be reached.
 */
export async function safePassthrough(request, env) {
  try {
    return await passthrough(request, env);
  } catch (e) {
    console.error("norg edge origin unreachable", e);
    return new Response("Service Unavailable", {
      status: 503,
      headers: { "Cache-Control": "private, no-store" },
    });
  }
}
