/**
 * Bundle the AWS edge-router sources into the deployable files in aws/src/.
 *
 * Usage: node aws/build.mjs   (or: npm run build:aws)
 *
 * aws/src/ holds COMMITTED build artifacts, for the same reasons as the
 * Cloudflare bundle: the CloudFormation templates and the attach CLI deploy
 * exactly those files, and NORG's backend pins them by SHA-256. CI rebuilds and
 * fails on any diff, so a source edit can never ship without its bundle.
 *
 * Three outputs, deployed to three different places:
 *   edge-router-lambda.cjs Lambda@Edge, origin-request.
 *   heartbeat-lambda.cjs   Regional Lambda on an EventBridge schedule.
 *   viewer-classifier.js   CloudFront Function. COPIED, never bundled — the
 *                          runtime is not Node, has a hard 10 KB ceiling, and
 *                          takes a bare script with a global `handler`.
 *
 * The Lambda bundles are CommonJS with an explicit .cjs extension. CJS because
 * Lambda@Edge is the conservative surface and every documented example uses it;
 * .cjs rather than .js because this repo's package.json declares
 * "type": "module", so a bundled .js would be unloadable locally — untestable
 * and confusing — even though Lambda would have read it correctly from a zip
 * with no package.json beside it.
 *
 * Two guards run before anything is written, both inherited from the Cloudflare
 * build because this artifact ships into third-party AWS accounts for the same
 * reason: no NORG-internal secret name may appear, and the router bundle must
 * be self-contained.
 *
 * esbuild is invoked through npx with a PINNED version rather than as a
 * package.json dependency, so the build is zero-install and deterministic.
 */

import { execFileSync } from "node:child_process";
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ESBUILD_VERSION = "0.25.5";

// Lambda@Edge supports the latest Node runtimes; pinned so a bundle cannot be
// built against syntax the deployed runtime does not have.
const NODE_TARGET = "node20";

// CloudFront's hard limit on a function's source size.
const CLOUDFRONT_FUNCTION_MAX_BYTES = 10 * 1024;

// Names that must NEVER appear in a bundle shipping into a customer's AWS
// account. Mirrors the Cloudflare build's list and content-craft's deploy-time
// guard, which refuses to upload a leaking artifact.
const FORBIDDEN_NAMES = [
  "CRAWLER_EVENT_SECRET",
  "WORKER_AUTH_SECRET",
  "R2_ACCESS_KEY_ID",
  "R2_SECRET_ACCESS_KEY",
  "INTERNAL_API_KEY",
  "EDGE_BUCKET",
];

const here = dirname(fileURLToPath(import.meta.url));
const srcDir = join(here, "src");

/**
 * Bundle one entry point into aws/src/.
 *
 * @param {string} name Basename shared by the source and the artifact.
 * @returns {string} The written bundle's contents.
 */
function bundle(name) {
  const entry = join(here, "lambda", `${name}.js`);
  const outfile = join(srcDir, `${name}.cjs`);

  execFileSync(
    "npx",
    [
      "--yes",
      `esbuild@${ESBUILD_VERSION}`,
      entry,
      "--bundle",
      "--format=cjs",
      "--platform=node",
      `--target=${NODE_TARGET}`,
      "--legal-comments=inline",
      `--outfile=${outfile}`,
      `--banner:js=// GENERATED by aws/build.mjs — do not edit.\n// Source: aws/lambda/${name}.js (+ aws/lambda/lib/, workers/lib/).`,
    ],
    { stdio: "inherit" },
  );
  // A bundle that fails to parse must fail the build, not the deploy.
  execFileSync("node", ["--check", outfile], { stdio: "inherit" });
  return readFileSync(outfile, "utf8");
}

/**
 * Refuse to publish a bundle carrying a NORG-internal secret name.
 *
 * @param {string} name Artifact name, for the message.
 * @param {string} contents Bundle contents.
 * @returns {void}
 */
function assertNoForbiddenNames(name, contents) {
  for (const forbidden of FORBIDDEN_NAMES) {
    if (contents.includes(forbidden)) {
      throw new Error(
        `refusing to publish: ${name} contains forbidden name "${forbidden}" — ` +
          "this must never reach a customer account",
      );
    }
  }
}

mkdirSync(srcDir, { recursive: true });

const router = bundle("edge-router-lambda");
const heartbeat = bundle("heartbeat-lambda");

assertNoForbiddenNames("edge-router-lambda.cjs", router);
assertNoForbiddenNames("heartbeat-lambda.cjs", heartbeat);

// The router must be self-contained: Lambda@Edge supports no layers, so an
// unresolved require() would fail at deploy rather than at build.
if (/\brequire\s*\(\s*["'](?!node:)/.test(router)) {
  throw new Error("refusing to publish: edge-router-lambda.cjs is not self-contained");
}

const functionSource = join(here, "functions", "viewer-classifier.js");
const functionOut = join(srcDir, "viewer-classifier.js");
copyFileSync(functionSource, functionOut);
assertNoForbiddenNames("viewer-classifier.js", readFileSync(functionOut, "utf8"));

const functionBytes = statSync(functionOut).size;
if (functionBytes > CLOUDFRONT_FUNCTION_MAX_BYTES) {
  throw new Error(
    `refusing to publish: viewer-classifier.js is ${functionBytes} bytes, ` +
      `over CloudFront's ${CLOUDFRONT_FUNCTION_MAX_BYTES}-byte function limit`,
  );
}

/**
 * Re-embed the CloudFront Function source into a CloudFormation template.
 *
 * The function is small enough to inline in a template (unlike the router,
 * which exceeds CloudFormation's 4 KB code limit and has to come from S3), and
 * inlining is what makes the stack self-contained. But an embedded copy drifts,
 * so it is GENERATED here rather than hand-maintained: CI rebuilds and fails on
 * any diff, exactly as it does for the bundles.
 *
 * @param {string} templatePath Absolute path to the template.
 * @param {string} functionCode CloudFront Function source.
 * @returns {void}
 */
function embedViewerClassifier(templatePath, functionCode) {
  const template = readFileSync(templatePath, "utf8");
  const indented = functionCode
    .split("\n")
    .map((line) => (line ? `        ${line}` : ""))
    .join("\n")
    .replace(/\s+$/, "");

  // Replace everything indented under `FunctionCode: |` up to the next key.
  const updated = template.replace(
    /( {6}FunctionCode: \|\n)(?: {8}.*\n| *\n)*/,
    `$1${indented}\n`,
  );
  if (updated === template && !template.includes(indented)) {
    throw new Error(`failed to embed viewer-classifier into ${templatePath}`);
  }
  writeFileSync(templatePath, updated);
}

for (const template of ["new-distribution.yaml", "attach-existing.yaml"]) {
  const templatePath = join(here, "cloudformation", template);
  if (existsSync(templatePath)) {
    embedViewerClassifier(templatePath, readFileSync(functionOut, "utf8"));
  }
}

const version = /EDGE_SCRIPT_VERSION\s*=\s*"([^"]+)"/.exec(router)?.[1];
console.log(`built aws/src/ (EDGE_SCRIPT_VERSION ${version})`);
console.log(`  edge-router-lambda.cjs ${statSync(join(srcDir, "edge-router-lambda.cjs")).size} bytes`);
console.log(`  heartbeat-lambda.cjs   ${statSync(join(srcDir, "heartbeat-lambda.cjs")).size} bytes`);
console.log(`  viewer-classifier.js   ${functionBytes} bytes`);
