/**
 * Bundle the AWS edge-router sources into the deployable files in aws/src/.
 *
 * Usage: node aws/build.mjs   (or: npm run build:aws)
 *
 * aws/src/ holds COMMITTED build artifacts, for the same reasons as the
 * Cloudflare bundle: the CloudFormation templates and the attach CLI deploy
 * exactly those files, and NORG's backend pins them by SHA-256. CI rebuilds and
 * fails on any diff, so a source edit can never ship without its bundle.
 *
 * Four outputs, deployed to four different places:
 *   edge-router-lambda.cjs Lambda@Edge, origin-request.
 *   cache-guard-lambda.cjs Lambda@Edge, origin-response. COPIED and inlined
 *                          into the templates (4 KB ZipFile ceiling), so it is
 *                          plain CommonJS with no imports.
 *   heartbeat-lambda.cjs   Regional Lambda on an EventBridge schedule.
 *   viewer-classifier.js   CloudFront Function. COPIED, never bundled — the
 *                          runtime is not Node, has a hard 10 KB ceiling, and
 *                          takes a bare script with a global `handler`.
 *
 * The Lambda bundles are CommonJS with an explicit .cjs extension. CJS because
 * Lambda@Edge is the conservative surface and every documented example uses it;
 * .cjs rather than .js because this repo's package.json declares
 * "type": "module", so a bundled .js would be unloadable locally — untestable
 * and confusing — even though Lambda would have read it correctly from a zip
 * with no package.json beside it.
 *
 * Two guards run before anything is written, both inherited from the Cloudflare
 * build because this artifact ships into third-party AWS accounts for the same
 * reason: no NORG-internal secret name may appear, and the router bundle must
 * be self-contained.
 *
 * esbuild is invoked through npx with a PINNED version rather than as a
 * package.json dependency, so the build is zero-install and deterministic.
 */

import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";

import {
  DEFAULT_ROUTE_EXCLUSIONS,
  DYNAMIC_ROUTE_EXCLUSIONS,
  MANAGED_ALL_VIEWER_EXCEPT_HOST_ORIGIN_REQUEST_ID,
  MANAGED_CACHING_DISABLED_ID,
  MCP_PATH_PATTERNS,
  PROTECTED_PATH_PREFIXES,
  TEMPLATE_ASSET_SUFFIXES,
} from "../core/exclusions.mjs";
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ESBUILD_VERSION = "0.25.5";

// Lambda@Edge supports the latest Node runtimes; pinned so a bundle cannot be
// built against syntax the deployed runtime does not have.
const NODE_TARGET = "node20";

// CloudFront's hard limit on a function's source size.
const CLOUDFRONT_FUNCTION_MAX_BYTES = 10 * 1024;

// CloudFormation's limit on Lambda code inlined as ZipFile. The cache guard is
// inlined (like the viewer classifier) so the stack stays self-contained.
const CFN_ZIPFILE_MAX_BYTES = 4 * 1024;

// Names that must NEVER appear in a bundle shipping into a customer's AWS
// account. Mirrors the Cloudflare build's list and content-craft's deploy-time
// guard, which refuses to upload a leaking artifact.
const FORBIDDEN_NAMES = [
  "CRAWLER_EVENT_SECRET",
  "WORKER_AUTH_SECRET",
  "R2_ACCESS_KEY_ID",
  "R2_SECRET_ACCESS_KEY",
  "INTERNAL_API_KEY",
  "EDGE_BUCKET",
];

const here = dirname(fileURLToPath(import.meta.url));
const srcDir = join(here, "src");

/**
 * Bundle one entry point into aws/src/.
 *
 * @param {string} name Basename shared by the source and the artifact.
 * @returns {string} The written bundle's contents.
 */
function bundle(name) {
  const entry = join(here, "lambda", `${name}.js`);
  const outfile = join(srcDir, `${name}.cjs`);

  execFileSync(
    "npx",
    [
      "--yes",
      `esbuild@${ESBUILD_VERSION}`,
      entry,
      "--bundle",
      "--format=cjs",
      "--platform=node",
      `--target=${NODE_TARGET}`,
      "--legal-comments=inline",
      `--outfile=${outfile}`,
      `--banner:js=// GENERATED by aws/build.mjs — do not edit.\n// Source: aws/lambda/${name}.js (+ core/, workers/lib/).`,
    ],
    { stdio: "inherit" },
  );
  // A bundle that fails to parse must fail the build, not the deploy.
  execFileSync("node", ["--check", outfile], { stdio: "inherit" });
  return readFileSync(outfile, "utf8");
}

/**
 * Refuse to publish a bundle carrying a NORG-internal secret name.
 *
 * @param {string} name Artifact name, for the message.
 * @param {string} contents Bundle contents.
 * @returns {void}
 */
function assertNoForbiddenNames(name, contents) {
  for (const forbidden of FORBIDDEN_NAMES) {
    if (contents.includes(forbidden)) {
      throw new Error(
        `refusing to publish: ${name} contains forbidden name "${forbidden}" — ` +
          "this must never reach a customer account",
      );
    }
  }
}

mkdirSync(srcDir, { recursive: true });

const router = bundle("edge-router-lambda");
const heartbeat = bundle("heartbeat-lambda");

assertNoForbiddenNames("edge-router-lambda.cjs", router);
assertNoForbiddenNames("heartbeat-lambda.cjs", heartbeat);

// The router must be self-contained: Lambda@Edge supports no layers, so an
// unresolved require() would fail at deploy rather than at build.
if (/\brequire\s*\(\s*["'](?!node:)/.test(router)) {
  throw new Error("refusing to publish: edge-router-lambda.cjs is not self-contained");
}

const functionSource = join(here, "functions", "viewer-classifier.js");
const functionOut = join(srcDir, "viewer-classifier.js");
copyFileSync(functionSource, functionOut);
assertNoForbiddenNames("viewer-classifier.js", readFileSync(functionOut, "utf8"));

const functionBytes = statSync(functionOut).size;
if (functionBytes > CLOUDFRONT_FUNCTION_MAX_BYTES) {
  throw new Error(
    `refusing to publish: viewer-classifier.js is ${functionBytes} bytes, ` +
      `over CloudFront's ${CLOUDFRONT_FUNCTION_MAX_BYTES}-byte function limit`,
  );
}

/**
 * Re-embed the CloudFront Function source into a CloudFormation template.
 *
 * The function is small enough to inline in a template (unlike the router,
 * which exceeds CloudFormation's 4 KB code limit and has to come from S3), and
 * inlining is what makes the stack self-contained. But an embedded copy drifts,
 * so it is GENERATED here rather than hand-maintained: CI rebuilds and fails on
 * any diff, exactly as it does for the bundles.
 *
 * @param {string} templatePath Absolute path to the template.
 * @param {string} functionCode CloudFront Function source.
 * @returns {void}
 */
function embedViewerClassifier(templatePath, functionCode) {
  const template = readFileSync(templatePath, "utf8");
  const indented = functionCode
    .split("\n")
    .map((line) => (line ? `        ${line}` : ""))
    .join("\n")
    .replace(/\s+$/, "");

  // Replace everything indented under `FunctionCode: |` up to the next key.
  const updated = template.replace(
    /( {6}FunctionCode: \|\n)(?: {8}.*\n| *\n)*/,
    `$1${indented}\n`,
  );
  if (updated === template && !template.includes(indented)) {
    throw new Error(`failed to embed viewer-classifier into ${templatePath}`);
  }
  writeFileSync(templatePath, updated);
}

const guardSource = join(here, "lambda", "cache-guard-lambda.cjs");
const guardOut = join(srcDir, "cache-guard-lambda.cjs");
copyFileSync(guardSource, guardOut);
const guardCode = readFileSync(guardOut, "utf8");
assertNoForbiddenNames("cache-guard-lambda.cjs", guardCode);
// Inlined, so it must stand alone: an import here would fail at deploy.
if (/\brequire\s*\(|^\s*import\s/m.test(guardCode)) {
  throw new Error("refusing to publish: cache-guard-lambda.cjs must have no imports (it is inlined)");
}
const guardBytes = statSync(guardOut).size;
if (guardBytes > CFN_ZIPFILE_MAX_BYTES) {
  throw new Error(
    `refusing to publish: cache-guard-lambda.cjs is ${guardBytes} bytes, ` +
      `over CloudFormation's ${CFN_ZIPFILE_MAX_BYTES}-byte ZipFile limit`,
  );
}
// AWS::Lambda::Version only republishes when ITS properties change, and an
// inlined ZipFile edit changes the function, not the version — so the guard
// would deploy to $LATEST while the distribution stayed on the old version,
// silently. The content hash in the Description is what forces a new one.
const guardDigest = createHash("sha256").update(guardCode).digest("hex").slice(0, 16);

/**
 * Re-embed the cache guard's source into a template's ZipFile block, and stamp
 * its digest into the Version resource so a code change publishes a version.
 *
 * @param {string} templatePath Absolute path to the template.
 * @param {string} code Guard source.
 * @returns {void}
 */
function embedCacheGuard(templatePath, code) {
  const template = readFileSync(templatePath, "utf8");
  const indented = code
    .split("\n")
    .map((line) => (line ? `          ${line}` : ""))
    .join("\n")
    .replace(/\s+$/, "");
  let updated = template.replace(
    /( {8}ZipFile: \|\n)(?: {10}.*\n| *\n)*/,
    `$1${indented}\n`,
  );
  updated = updated.replace(
    /(Description: "cache-guard sha256:)[0-9a-f]*(")/,
    `$1${guardDigest}$2`,
  );
  if (!updated.includes(indented) || !updated.includes(guardDigest)) {
    throw new Error(`failed to embed cache-guard into ${templatePath}`);
  }
  writeFileSync(templatePath, updated);
}

for (const template of ["new-distribution.yaml", "attach-existing.yaml"]) {
  const templatePath = join(here, "cloudformation", template);
  if (existsSync(templatePath)) {
    embedViewerClassifier(templatePath, readFileSync(functionOut, "utf8"));
    embedCacheGuard(templatePath, guardCode);
  }
}

/**
 * Refuse a carve-out pattern that would shadow a path NORG serves itself.
 *
 * CloudFront matches cache behaviours in listed order and the first match wins,
 * so a carve-out placed above the default behaviour silently takes the router
 * out of the loop for anything it matches. Mirrors route_scope's
 * _exclusion_shadow_error, which exists because the same mistake on Cloudflare
 * switches off MCP, discovery and the agentic subtree with no error anywhere.
 *
 * @param {string} pattern CloudFront path pattern.
 * @returns {void}
 */
function assertDoesNotShadowNorg(pattern) {
  // A suffix pattern (*.css) can only match on extension, and the protected
  // paths deliberately use none that appear in the asset list — see
  // WORKER_EXEMPT_SUFFIXES. Only prefix carve-outs can reach them.
  if (pattern.startsWith("*")) return;
  const prefix = pattern.replace(/\*+$/, "");
  for (const protectedPath of PROTECTED_PATH_PREFIXES) {
    if (protectedPath.startsWith(prefix) || prefix.startsWith(protectedPath)) {
      throw new Error(
        `refusing to publish: carve-out "${pattern}" shadows NORG-served path ` +
          `"${protectedPath}" — CloudFront would stop invoking the router for it`,
      );
    }
  }
}

/**
 * Render one no-Lambda, cached carve-out for a static asset pattern.
 *
 * @param {string} pattern CloudFront path pattern.
 * @returns {string} Indented YAML for one CacheBehaviors entry.
 */
function cacheBehaviour(pattern) {
  assertDoesNotShadowNorg(pattern);
  return [
    `          - PathPattern: "${pattern}"`,
    "            TargetOriginId: customer-origin",
    "            ViewerProtocolPolicy: redirect-to-https",
    "            Compress: true",
    // No CachedMethods: CloudFront's default of [GET, HEAD] is right for an
    // asset, and the template is byte-budgeted (see the size guard below).
    "            AllowedMethods: [GET, HEAD, OPTIONS]",
    "            CachePolicyId: !Ref StaticCachePolicy",
  ].join("\n");
}

/**
 * Render one no-Lambda, NO-CACHE carve-out for a dynamic path.
 *
 * CachingDisabled + AllViewer: the origin sees exactly the request it would
 * have seen without the router, nothing is stored, and every method is
 * allowed because these are the paths that take POSTs.
 *
 * @param {string} pattern CloudFront path pattern.
 * @returns {string} Indented YAML for one CacheBehaviors entry.
 */
function dynamicBehaviour(pattern) {
  assertDoesNotShadowNorg(pattern);
  return [
    `          - PathPattern: "${pattern}"`,
    "            TargetOriginId: customer-origin",
    "            ViewerProtocolPolicy: redirect-to-https",
    "            Compress: true",
    "            AllowedMethods: [GET, HEAD, OPTIONS, PUT, POST, PATCH, DELETE]",
    "            CachedMethods: [GET, HEAD, OPTIONS]",
    `            CachePolicyId: ${MANAGED_CACHING_DISABLED_ID}`,
    `            OriginRequestPolicyId: ${MANAGED_ALL_VIEWER_EXCEPT_HOST_ORIGIN_REQUEST_ID}`,
  ].join("\n");
}

/**
 * Render one MCP behaviour: the full router, and the ONLY place IncludeBody is on.
 *
 * Deliberately not run through the shadow guard — these paths are NORG-served
 * by design, and the whole point is that the router is attached here.
 *
 * @param {string} pattern CloudFront path pattern.
 * @returns {string} Indented YAML for one CacheBehaviors entry.
 */
function mcpBehaviour(pattern) {
  return [
    `          - PathPattern: "${pattern}"`,
    "            TargetOriginId: customer-origin",
    "            ViewerProtocolPolicy: redirect-to-https",
    "            Compress: true",
    "            AllowedMethods: [GET, HEAD, OPTIONS, PUT, POST, PATCH, DELETE]",
    "            CachedMethods: [GET, HEAD, OPTIONS]",
    "            CachePolicyId: !Ref CachePolicy",
    "            OriginRequestPolicyId: !Ref OriginRequestPolicy",
    "            FunctionAssociations:",
    "              - EventType: viewer-request",
    "                FunctionARN: !GetAtt ViewerClassifier.FunctionARN",
    "            LambdaFunctionAssociations:",
    "              - EventType: origin-request",
    "                LambdaFunctionARN: !Ref EdgeRouterVersion",
    "                IncludeBody: true",
    "              - EventType: origin-response",
    "                LambdaFunctionARN: !Ref CacheGuardVersion",
  ].join("\n");
}

/**
 * Regenerate the carve-out cache behaviours inside a template.
 *
 * Match order is load-bearing (first match wins): MCP paths first, then the
 * dynamic no-cache carve-outs, then framework prefixes, then the bare asset
 * suffixes — each group more specific than the one after it.
 *
 * @param {string} templatePath Absolute path to the template.
 * @param {Array<{pattern: string, render: function(string): string}>} entries
 *   Patterns with their renderer, in match order.
 * @returns {number} How many behaviours were written.
 */
function embedCacheBehaviours(templatePath, entries) {
  const template = readFileSync(templatePath, "utf8");
  const body = entries.map(({ pattern, render }) => render(pattern)).join("\n");
  const updated = template.replace(
    /( *# BEGIN GENERATED CACHE BEHAVIOURS\n)[\s\S]*?( *# END GENERATED CACHE BEHAVIOURS)/,
    `$1${body}\n$2`,
  );
  if (updated === template && !template.includes(body)) {
    throw new Error(`failed to embed cache behaviours into ${templatePath}`);
  }
  writeFileSync(templatePath, updated);
  return entries.length;
}

const carveOuts = [
  ...MCP_PATH_PATTERNS.map((pattern) => ({ pattern, render: mcpBehaviour })),
  ...DYNAMIC_ROUTE_EXCLUSIONS.map((pattern) => ({ pattern, render: dynamicBehaviour })),
  ...DEFAULT_ROUTE_EXCLUSIONS.map((pattern) => ({ pattern, render: cacheBehaviour })),
  ...TEMPLATE_ASSET_SUFFIXES.map((suffix) => ({ pattern: `*${suffix}`, render: cacheBehaviour })),
];
const behaviourCount = embedCacheBehaviours(
  join(here, "cloudformation", "new-distribution.yaml"),
  carveOuts,
);
// CloudFront allows 75 cache behaviours per distribution; the default one is
// included in that count.
if (behaviourCount + 1 > 75) {
  throw new Error(`refusing to publish: ${behaviourCount + 1} cache behaviours exceeds CloudFront's limit of 75`);
}

// CloudFormation refuses a template body over 51,200 bytes (validate-template,
// create-stack and the console paste all hit it; only an S3 template URL is
// bigger). The behaviours block is the swing factor, which is why the template
// carries TEMPLATE_ASSET_SUFFIXES rather than the full list. Fail here, at
// build time, rather than at a customer's first `aws cloudformation deploy`.
const CFN_TEMPLATE_BODY_MAX_BYTES = 51_200;
for (const template of ["new-distribution.yaml", "attach-existing.yaml"]) {
  const bytes = statSync(join(here, "cloudformation", template)).size;
  if (bytes > CFN_TEMPLATE_BODY_MAX_BYTES) {
    throw new Error(
      `refusing to publish: ${template} is ${bytes} bytes, over CloudFormation's ` +
        `${CFN_TEMPLATE_BODY_MAX_BYTES}-byte template-body limit — trim TEMPLATE_ASSET_SUFFIXES`,
    );
  }
}

const version = /EDGE_SCRIPT_VERSION\s*=\s*"([^"]+)"/.exec(router)?.[1];
console.log(`built aws/src/ (EDGE_SCRIPT_VERSION ${version})`);
console.log(`  cache behaviours       ${behaviourCount} carve-outs (+1 default)`);
console.log(`  new-distribution.yaml  ${statSync(join(here, "cloudformation", "new-distribution.yaml")).size} bytes (limit ${CFN_TEMPLATE_BODY_MAX_BYTES})`);
console.log(`  edge-router-lambda.cjs ${statSync(join(srcDir, "edge-router-lambda.cjs")).size} bytes`);
console.log(`  cache-guard-lambda.cjs ${guardBytes} bytes (sha256:${guardDigest})`);
console.log(`  heartbeat-lambda.cjs   ${statSync(join(srcDir, "heartbeat-lambda.cjs")).size} bytes`);
console.log(`  viewer-classifier.js   ${functionBytes} bytes`);
