// GENERATED by aws/build.mjs — do not edit.
// Source: aws/lambda/heartbeat-lambda.js (+ aws/lambda/lib/, workers/lib/).
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// aws/lambda/heartbeat-lambda.js
var heartbeat_lambda_exports = {};
__export(heartbeat_lambda_exports, {
  default: () => heartbeat_lambda_default,
  handler: () => handler
});
module.exports = __toCommonJS(heartbeat_lambda_exports);

// aws/lambda/lib/constants.mjs
var CONTROL_CALL_TIMEOUT_MS = 3e3;
var PATTERN_DEFAULT_TTL_MS = 3600 * 1e3;
var UNENTITLED_TTL_MS = 60 * 1e3;
var HEARTBEAT_MIN_INTERVAL_MS = 15 * 60 * 1e3;
var RENDER_DEDUP_TTL_MS = 10 * 60 * 1e3;
var UNENTITLED = Object.freeze({
  entitled: false,
  patterns: [],
  cidrRanges: {},
  agenticPathPrefix: "",
  skipPaths: []
});

// aws/lambda/lib/config.js
var EDGE_SCRIPT_VERSION = "0.2.0";

// aws/lambda/heartbeat-lambda.js
async function handler() {
  const {
    SITE_ID,
    NORG_SITE_KEY,
    NORG_API_URL = "https://content-craft-api.norg.ai",
    EDGE_ENV = "unknown"
  } = process.env;
  if (!SITE_ID || !NORG_SITE_KEY) {
    throw new Error("norg edge heartbeat: SITE_ID and NORG_SITE_KEY are required");
  }
  const response = await fetch(`${NORG_API_URL}/api/v1/edge/heartbeat`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "X-Norg-Site-Id": SITE_ID,
      "X-Norg-Site-Key": NORG_SITE_KEY,
      "X-Norg-Edge-Version": EDGE_SCRIPT_VERSION
    },
    body: JSON.stringify({
      script_version: EDGE_SCRIPT_VERSION,
      trigger: "cron",
      env: EDGE_ENV,
      platform: "cloudfront"
    }),
    signal: AbortSignal.timeout(CONTROL_CALL_TIMEOUT_MS)
  });
  if (!response.ok) {
    throw new Error(`norg edge heartbeat rejected: HTTP ${response.status}`);
  }
  return response.json();
}
var heartbeat_lambda_default = handler;
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  handler
});
