// GENERATED by aws/build.mjs — do not edit.
// Source: aws/lambda/heartbeat-lambda.js (+ core/, workers/lib/).
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// aws/lambda/heartbeat-lambda.js
var heartbeat_lambda_exports = {};
__export(heartbeat_lambda_exports, {
  default: () => heartbeat_lambda_default,
  handler: () => handler
});
module.exports = __toCommonJS(heartbeat_lambda_exports);

// core/constants.mjs
var CONTROL_CALL_TIMEOUT_MS = 3e3;
var PATTERN_DEFAULT_TTL_MS = 3600 * 1e3;
var UNENTITLED_TTL_MS = 60 * 1e3;
var HEARTBEAT_MIN_INTERVAL_MS = 15 * 60 * 1e3;
var RENDER_DEDUP_TTL_MS = 10 * 60 * 1e3;
var UNENTITLED = Object.freeze({
  entitled: false,
  patterns: [],
  cidrRanges: {},
  agenticPathPrefix: "",
  skipPaths: []
});

// aws/lambda/lib/config.js
var EDGE_SCRIPT_VERSION = "0.6.0";

// aws/lambda/lib/secret.js
var CACHE_TTL_MS = 15 * 60 * 1e3;
var SECRET_TIMEOUT_MS = 1500;
var SECRET_REGION = "us-east-1";
var EDGE_REGIONS = /* @__PURE__ */ new Set([
  "us-east-1",
  "us-east-2",
  "us-west-1",
  "us-west-2",
  "ap-south-1",
  "ap-northeast-1",
  "ap-northeast-2",
  "ap-southeast-1",
  "ap-southeast-2",
  "eu-central-1",
  "eu-west-1",
  "eu-west-2",
  "sa-east-1"
]);
var cached = { value: null, fetchedAt: 0 };
var replicaMissing = false;
function loadClient() {
  return require("@aws-sdk/client-secrets-manager");
}
function parseSecret(secretString) {
  if (!secretString) return null;
  const trimmed = secretString.trim();
  if (!trimmed.startsWith("{")) return trimmed || null;
  try {
    const parsed = JSON.parse(trimmed);
    return parsed?.NORG_SITE_KEY || parsed?.site_key || null;
  } catch (e) {
    return null;
  }
}
function regionalArn(arn, region) {
  const parts = String(arn).split(":");
  if (parts.length < 7 || parts[2] !== "secretsmanager") return null;
  parts[3] = region;
  return parts.join(":");
}
function localReadRegion(arn) {
  const region = typeof process !== "undefined" ? process.env.AWS_REGION : void 0;
  if (!region || !EDGE_REGIONS.has(region) || replicaMissing) return null;
  const primary = String(arn).split(":")[3];
  return region === primary ? null : region;
}
async function readSecret(arn, region) {
  const { SecretsManagerClient, GetSecretValueCommand } = loadClient();
  const client = new SecretsManagerClient({ region });
  const result = await client.send(new GetSecretValueCommand({ SecretId: arn }), {
    abortSignal: AbortSignal.timeout(SECRET_TIMEOUT_MS)
  });
  return parseSecret(result?.SecretString);
}
async function readNearest(arn) {
  const region = localReadRegion(arn);
  if (region) {
    try {
      const value = await readSecret(regionalArn(arn, region), region);
      if (value) return value;
    } catch (e) {
      replicaMissing = true;
      console.error("norg site key replica read failed, using primary", region, e?.name || e);
    }
  }
  return readSecret(arn, SECRET_REGION);
}
async function getSiteKey(env) {
  const arn = env?.NORG_SECRET_ARN;
  if (!arn) return null;
  const age = Date.now() - cached.fetchedAt;
  if (cached.value && age < CACHE_TTL_MS) return cached.value;
  try {
    const value = await readNearest(arn);
    if (!value) return null;
    cached = { value, fetchedAt: Date.now() };
    return value;
  } catch (e) {
    console.error("norg site key fetch failed", e);
    return null;
  }
}

// aws/lambda/heartbeat-lambda.js
async function handler() {
  const {
    SITE_ID,
    NORG_SECRET_ARN,
    NORG_API_URL = "https://content-craft-api.norg.ai",
    EDGE_ENV = "unknown"
  } = process.env;
  if (!SITE_ID || !NORG_SECRET_ARN) {
    throw new Error("norg edge heartbeat: SITE_ID and NORG_SECRET_ARN are required");
  }
  const NORG_SITE_KEY = await getSiteKey({ NORG_SECRET_ARN });
  if (!NORG_SITE_KEY) {
    throw new Error(`norg edge heartbeat: could not read the site key from ${NORG_SECRET_ARN}`);
  }
  const response = await fetch(`${NORG_API_URL}/api/v1/edge/heartbeat`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "X-Norg-Site-Id": SITE_ID,
      "X-Norg-Site-Key": NORG_SITE_KEY,
      "X-Norg-Edge-Version": EDGE_SCRIPT_VERSION
    },
    body: JSON.stringify({
      script_version: EDGE_SCRIPT_VERSION,
      trigger: "cron",
      env: EDGE_ENV,
      platform: "cloudfront"
    }),
    signal: AbortSignal.timeout(CONTROL_CALL_TIMEOUT_MS)
  });
  if (!response.ok) {
    throw new Error(`norg edge heartbeat rejected: HTTP ${response.status}`);
  }
  return response.json();
}
var heartbeat_lambda_default = handler;
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  handler
});
